/*
 * Generated by ooc, the Object-Oriented C compiler, by Amos Wenger, 2009
 */

// OOC dependencies
#include "example1.h"

/*
 * Definition of class MyObject
 */

MyObject__class MyObject__classInstance;


Void __MyObject_sayHello(struct MyObject*  this) {
	
	printf("Hi dude, my name is %s, and I'm happy to meet you!\n", this->name);
	printfd();


}

struct MyObject*  __MyObject_new_String(String name) {

	MyObject this = GC_malloc(sizeof(struct MyObject));

	if(MyObject__classInstance == NULL) {
		MyObject__classInstance = GC_malloc(sizeof(struct MyObject__class));
		MyObject__classInstance ->name = "MyObject";
	}
	this->class = MyObject__classInstance;

	this->class->__sayHello = (Void (*)(struct MyObject* )) &__MyObject_sayHello;
	
	this->name = name;

	return this;


}

Int main() {

	GC_init();	
	printf("Trying to create object..\n");
	struct MyObject*  object = __MyObject_new_String("Smith");
	printf("Trying to say hello\n");
	object->class->__sayHello(object);
	printf("Returning\n");
	return 0;


}
