/*
 * Generated by ooc, the Object-Oriented C compiler, by Amos Wenger, 2009
 */

// OOC dependencies
#include "MouseEvent.h"

/*
 * Definition of class MouseEvent
 */

Int MouseEvent_CLIC = 0;

Int MouseEvent_OVER = 1;

MouseEvent__class MouseEvent__classInstance;


struct MouseEvent*  __MouseEvent_new_Int_Int_Int(Int eventType, Int x, Int y) {

	MouseEvent this = GC_malloc(sizeof(struct MouseEvent));

	if(MouseEvent__classInstance == NULL) {
		MouseEvent__classInstance = GC_malloc(sizeof(struct MouseEvent__class));
		MouseEvent__classInstance->name = "MouseEvent";
		MouseEvent__classInstance->simpleName = "MouseEvent";
	}
	this->class = MouseEvent__classInstance;

	
	this->x = x;
	this->y = y;
	Int type = eventType;
	this->type = type;;

	return this;


}
