/*
 * Generated by ooc, the Object-Oriented C compiler, by Amos Wenger, 2009
 */

// OOC dependencies
#include "minimal.h"

/*
 * Definition of class Blah
 */

Blah__class Blah__classInstance;


struct Blah*  __Blah_new() {

	Blah this = GC_malloc(sizeof(struct Blah));

	if(Blah__classInstance == NULL) {
		Blah__classInstance = GC_malloc(sizeof(struct Blah__class));
		Blah__classInstance ->name = "Blah";
	}
	this->class = Blah__classInstance;

	
	this->b->class.name;

	return this;


}

Int main() {

	GC_init();	


};
