/*
 * Generated by ooc, the Object-Oriented C compiler, by Amos Wenger, 2009
 */

// OOC dependencies
#include "tree.h"


Int main(Int argc, String argv[]) {

	GC_init();	
	__gtk_Gtk_init_Int__star_String__star__star(& argc, & argv);
	struct gtk_Window*  window = __gtk_Window_new_String("Rock Tree Test");
	window->class->__setUSize_gint_gint(window, 640, 480);
	window->class->__connectNaked_String_Func(window, "delete_event", ((Func) __gtk_Gtk_mainQuit));
	Int types[] = {
		
		G_TYPE_STRING,  G_TYPE_STRING,
	};
	struct gtk_TreeStore*  store = __gtk_TreeStore_new_int_Int__array(NUM_COLS, types);
	struct gtk_TreeNode*  root1 = __gtk_TreeNode_new_TreeStore(store);
	root1->class->__setValue_int_Object(root1, COL_TITLE, "root1");
	root1->class->__setValue_int_Object(root1, COL_DESC, "First root node");
	struct gtk_TreeNode*  root2 = __gtk_TreeNode_new_TreeStore(store);
	root2->class->__setValue_int_Object(root2, COL_TITLE, "root2");
	root2->class->__setValue_int_Object(root2, COL_DESC, "Second root node");
	struct gtk_TreeNode*  child1 = __gtk_TreeNode_new_TreeStore_gtk_TreeNode(store, root2);
	child1->class->__setValue_int_Object(child1, COL_TITLE, "child1");
	child1->class->__setValue_int_Object(child1, COL_DESC, "First Child node");
	struct gtk_TreeNode*  grandChild1 = __gtk_TreeNode_new_TreeStore_gtk_TreeNode(store, child1);
	grandChild1->class->__setValue_int_Object(grandChild1, COL_TITLE, "grandChild1");
	grandChild1->class->__setValue_int_Object(grandChild1, COL_DESC, "First Grand Child node");
	struct gtk_TreeView*  treeView = __gtk_TreeView_new_TreeModel(store);
	treeView->class->__appendColumn_TreeViewColumn(treeView, __gtk_TreeViewColumn_new_String_Int("Title",  COL_TITLE));
	treeView->class->__appendColumn_TreeViewColumn(treeView, __gtk_TreeViewColumn_new_String_Int("Description",  COL_DESC));
	window->class->__add_Widget(window, treeView);
	window->class->__showAll(window);
	if(argc >= 2 && argv[1].length) {
		return 1;
	}
	__gtk_Gtk_main();


}
