/*
 * Generated by ooc, the Object-Oriented C compiler, by Amos Wenger, 2009
 */

// OOC dependencies
#include "Container.h"


/**
 * A container is a widget that can contain other widgets
 */

/*
 * Definition of class gtk.Container
 */

gtk_Container__class gtk_Container__classInstance;


/**
 * Add a widget to this container
 * @param widget the widget to add
 */
Void __gtk_Container_add_Widget(struct gtk_Container*  this, struct gtk_Widget*  widget) {
	
	gtk_container_add(GTK_CONTAINER(this->class->__getWidget(this)), widget->class->__getWidget(widget));


}

/**
 * Remove a widget from this container
 * @param widget the widget to remove
 */
Void __gtk_Container_remove_Widget(struct gtk_Container*  this, struct gtk_Widget*  widget) {
	
	gtk_container_remove(GTK_CONTAINER(this->class->__getWidget(this)), widget->class->__getWidget(widget));


}

/**
 * Change the width of the border of this container
 * @param width
 */
Void __gtk_Container_setBorderWidth_Int(struct gtk_Container*  this, Int width) {
	
	gtk_container_set_border_width(GTK_CONTAINER(this->class->__getWidget(this)), width);


}
