/*
 * Generated by ooc, the Object-Oriented C compiler, by Amos Wenger, 2009
 */

// OOC dependencies
#include "GObject.h"


/**
 * Typedefs
 */

/*
 * Definition of class gtk.SignalPacket
 */

gtk_SignalPacket__class gtk_SignalPacket__classInstance;


Void __gtk_SignalPacket_call(struct gtk_SignalPacket*  this) {
	
	// printf("[SignalPacket] Forwarding callback on a %s with data '%s'!\n", object.class->name, (String) data); 

	this->callback(this->object, this->data);


}

struct gtk_SignalPacket*  __gtk_SignalPacket_new_GObject_GPointer_Func(struct gtk_GObject*  object, GPointer data, Func callback) {

	gtk_SignalPacket this = GC_malloc(sizeof(struct gtk_SignalPacket));

	if(gtk_SignalPacket__classInstance == NULL) {
		gtk_SignalPacket__classInstance = GC_malloc(sizeof(struct gtk_SignalPacket__class));
		gtk_SignalPacket__classInstance ->name = "gtk.SignalPacket";
	}
	this->class = gtk_SignalPacket__classInstance;

	this->class->__call = (Void (*)(struct gtk_SignalPacket* )) &__gtk_SignalPacket_call;
	
	this->object = object;
	this->data = data;
	this->callback = callback;
	// printf("new SignalPacket created with a %s and data '%s'\n", object.class->name, (String) data); 


	return this;


}

Void __signalWrapper_GtkObject__star_GPointer(GtkObject *object, GPointer data) {
	
	// printf("[SignalPacket] signalWrapper, got called!\n"); 

	struct gtk_SignalPacket*  packet =((gtk_SignalPacket) data);
	packet->class->__call(packet);


}

/**
 * The base of the GObject hierarchy. Can send and receive signals
 */

/*
 * Definition of class gtk.GObject
 */

gtk_GObject__class gtk_GObject__classInstance;


/**
 * must be implemented by any child class
 */


/**
 * Connect a callback to a signal
 * @param signalName the name of the signal to connect to
 * @param callback a pointer to the Func to call whenever
 * this signal is received
 */
Void __gtk_GObject_connect_String_Func(struct gtk_GObject*  this, String signalName, Func callback) {
	
	this->class->__connect_String_Func_GPointer(this, signalName, callback, NULL);


}

/**
 * Connect a callback to a signal
 * @param signalName the name of the signal to connect to
 * @param callback a pointer to the Func to call whenever
 * this signal is received
 * @param data data to be passed as an argument to the callback
 */
Void __gtk_GObject_connect_String_Func_GPointer(struct gtk_GObject*  this, String signalName, Func callback, GPointer data) {
	
	GULong id = gtk_signal_connect(GTK_OBJECT(this->class->__getObject(this)), signalName, GTK_SIGNAL_FUNC(__signalWrapper_GtkObject__star_GPointer), __gtk_SignalPacket_new_GObject_GPointer_Func(this, data, callback));


}

Void __gtk_GObject_connectNaked_String_Func(struct gtk_GObject*  this, String signalName, Func callback) {
	
	GULong id = gtk_signal_connect(GTK_OBJECT(this->class->__getObject(this)), signalName, GTK_SIGNAL_FUNC(callback), NULL);


}

Void __gtk_GObject_connectNaked_String_Func_GPointer(struct gtk_GObject*  this, String signalName, Func callback, GPointer data) {
	
	GULong id = gtk_signal_connect(GTK_OBJECT(this->class->__getObject(this)), signalName, GTK_SIGNAL_FUNC(callback), data);


}

Void __gtk_GObject_emitByName_String(struct gtk_GObject*  this, String signalName) {
	
	gtk_signal_emit_by_name(GTK_OBJECT(this->class->__getObject(this)), signalName);


}

/**
 * Add a reference to this object, thus preventing its destruction
 */
Void __gtk_GObject_ref(struct gtk_GObject*  this) {
	
	gtk_object_ref(this->class->__getObject(this));


}

/**
 * Release a reference from this object
 */
Void __gtk_GObject_unref(struct gtk_GObject*  this) {
	
	gtk_object_unref(this->class->__getObject(this));


}

/**
 * 'Take ownership' of this object, ie. remove its initial reference
 */
Void __gtk_GObject_sink(struct gtk_GObject*  this) {
	
	gtk_object_sink(this->class->__getObject(this));


}

/**
 * Sets a property on an object.
 * @param propertyName the name of the property to set
 * @param value the value
 */
Void __gtk_GObject_setProperty_String_GValue__star(struct gtk_GObject*  this, String name, GValue *value) {
	
	g_object_set_property(this->class->__getObject(this), name, value);


}
