/*
 * Generated by ooc, the Object-Oriented C compiler, by Amos Wenger, 2009
 */

// OOC dependencies
#include "IconSet.h"

/*
 * Definition of class gtk.IconSet
 */

gtk_IconSet__class gtk_IconSet__classInstance;


GtkIconSet * __gtk_IconSet_getIconSet(struct gtk_IconSet*  this) {
	
	return this->iconSet;


}

struct gtk_IconSet*  __gtk_IconSet_new_GtkIconSet__star(GtkIconSet *iconSet) {

	gtk_IconSet this = GC_malloc(sizeof(struct gtk_IconSet));

	if(gtk_IconSet__classInstance == NULL) {
		gtk_IconSet__classInstance = GC_malloc(sizeof(struct gtk_IconSet__class));
		gtk_IconSet__classInstance ->name = "gtk.IconSet";
	}
	this->class = gtk_IconSet__classInstance;

	this->class->__getIconSet = (GtkIconSet * (*)(struct gtk_IconSet* )) &__gtk_IconSet_getIconSet;
	
	this->iconSet = iconSet;

	return this;


}
