/*
 * Generated by ooc, the Object-Oriented C compiler, by Amos Wenger, 2009
 */

// OOC dependencies
#include "Style.h"

/*
 * Definition of class gtk.Style
 */

gtk_Style__class gtk_Style__classInstance;


struct gtk_IconSet*  __gtk_Style_lookupIconSet_String(struct gtk_Style*  this, String stockId) {
	
	GtkIconSet * iconSet = gtk_style_lookup_icon_set(this->style, stockId);
	if(iconSet) {
		return __gtk_IconSet_new_GtkIconSet__star(iconSet);
	}
	else {
		return NULL;
	}


} struct gtk_Style*  __gtk_Style_new_GtkStyle__star(GtkStyle *style) {

	gtk_Style this = GC_malloc(sizeof(struct gtk_Style));

	if(gtk_Style__classInstance == NULL) {
		gtk_Style__classInstance = GC_malloc(sizeof(struct gtk_Style__class));
		gtk_Style__classInstance ->name = "gtk.Style";
	}
	this->class = gtk_Style__classInstance;

	this->class->__lookupIconSet_String = (struct gtk_IconSet*  (*)(struct gtk_Style* , String)) &__gtk_Style_lookupIconSet_String;
	
	this->style = style; return this; 
}
