/*
 * Generated by ooc, the Object-Oriented C compiler, by Amos Wenger, 2009
 */

// OOC dependencies
#include "TreeNode.h"

/*
 * Definition of class gtk.TreeNode
 */

gtk_TreeNode__class gtk_TreeNode__classInstance;


/**
 * Set the value of the first column
 */
Void __gtk_TreeNode_setValue_Object(struct gtk_TreeNode*  this, Object value) {
	
	gtk_tree_store_set(this->store->store, & this->iter, 0, value, -1);


}

Void __gtk_TreeNode_setValue_int_Object(struct gtk_TreeNode*  this, int column, Object value) {
	
	gtk_tree_store_set(this->store->store, & this->iter, column, value, -1);


}

struct gtk_TreeNode*  __gtk_TreeNode_new_TreeStore(struct gtk_TreeStore*  store) {

	gtk_TreeNode this = GC_malloc(sizeof(struct gtk_TreeNode));

	if(gtk_TreeNode__classInstance == NULL) {
		gtk_TreeNode__classInstance = GC_malloc(sizeof(struct gtk_TreeNode__class));
		gtk_TreeNode__classInstance ->name = "gtk.TreeNode";
	}
	this->class = gtk_TreeNode__classInstance;

	this->class->__setValue_Object = (Void (*)(struct gtk_TreeNode* , Object)) &__gtk_TreeNode_setValue_Object;
	this->class->__setValue_int_Object = (Void (*)(struct gtk_TreeNode* , int, Object)) &__gtk_TreeNode_setValue_int_Object;
	
	this->store = store;
	gtk_tree_store_append(this->store->store, & this->iter, NULL);

	return this;


}

struct gtk_TreeNode*  __gtk_TreeNode_new_TreeStore_gtk_TreeNode(struct gtk_TreeStore*  store, struct gtk_TreeNode*  parent) {

	gtk_TreeNode this = GC_malloc(sizeof(struct gtk_TreeNode));

	if(gtk_TreeNode__classInstance == NULL) {
		gtk_TreeNode__classInstance = GC_malloc(sizeof(struct gtk_TreeNode__class));
		gtk_TreeNode__classInstance ->name = "gtk.TreeNode";
	}
	this->class = gtk_TreeNode__classInstance;

	this->class->__setValue_Object = (Void (*)(struct gtk_TreeNode* , Object)) &__gtk_TreeNode_setValue_Object;
	this->class->__setValue_int_Object = (Void (*)(struct gtk_TreeNode* , int, Object)) &__gtk_TreeNode_setValue_int_Object;
	
	this->store = store;
	gtk_tree_store_append(this->store->store, & this->iter, & parent->iter);

	return this;


}
