/*
 * Generated by ooc, the Object-Oriented C compiler, by Amos Wenger, 2009
 */

// OOC dependencies
#include "TreeStore.h"


/**
 * A tree-like data structure that can be used with the TreeView
 */

/*
 * Definition of class gtk.TreeStore
 */

gtk_TreeStore__class gtk_TreeStore__classInstance;


GtkTreeModel * __gtk_TreeStore_getModel(struct gtk_TreeStore*  this) {
	
	return GTK_TREE_MODEL(this->store);


}

/**
 * Create a new TreeStore with one column of type G_TYPE_STRING
 */
struct gtk_TreeStore*  __gtk_TreeStore_new() {

	gtk_TreeStore this = GC_malloc(sizeof(struct gtk_TreeStore));

	if(gtk_TreeStore__classInstance == NULL) {
		gtk_TreeStore__classInstance = GC_malloc(sizeof(struct gtk_TreeStore__class));
		gtk_TreeStore__classInstance ->name = "gtk.TreeStore";
	}
	this->class = gtk_TreeStore__classInstance;

	this->class->__getModel = (GtkTreeModel * (*)(struct gtk_TreeStore* )) &__gtk_TreeStore_getModel;
	
	this->store = gtk_tree_store_new(1,  G_TYPE_STRING);

	return this;


}

/**
 * Create a new TreeStore with 'numColumns' columns of type
 * 'types'
 */
struct gtk_TreeStore*  __gtk_TreeStore_new_int_Int__array(int numColumns, Int types[]) {

	gtk_TreeStore this = GC_malloc(sizeof(struct gtk_TreeStore));

	if(gtk_TreeStore__classInstance == NULL) {
		gtk_TreeStore__classInstance = GC_malloc(sizeof(struct gtk_TreeStore__class));
		gtk_TreeStore__classInstance ->name = "gtk.TreeStore";
	}
	this->class = gtk_TreeStore__classInstance;

	this->class->__getModel = (GtkTreeModel * (*)(struct gtk_TreeStore* )) &__gtk_TreeStore_getModel;
	
	this->store = gtk_tree_store_newv(numColumns, types);

	return this;


}
