/*
 * Generated by ooc, the Object-Oriented C compiler, by Amos Wenger, 2009
 */

// OOC dependencies
#include "TreeModel.h"


/**
 * The tree interface used by GtkTreeView
 */

/*
 * Definition of class gtk.TreeModel
 */

gtk_TreeModel__class gtk_TreeModel__classInstance;

