/*
 * Generated by ooc, the Object-Oriented C compiler, by Amos Wenger, 2009
 */

// OOC dependencies
#include "Widget.h"


/**
 * A GTK widget, such as a Button, a Label, a Checkbox
 */

/*
 * Definition of class gtk.Widget
 */

gtk_Widget__class gtk_Widget__classInstance;


GtkWidget * __gtk_Widget_getWidget(struct gtk_Widget*  this) {
	
	return GTK_WIDGET(this->class->__getObject(this));


}

/**
 * Set the sensitivity of this widget
 * @param sensitive if true, the widget will react to the user
 * input, and send/receive signals as usual. If false, thewidget
 * will be "grayed out" and won't react to anything
 */
Void __gtk_Widget_setSensitive_Bool(struct gtk_Widget*  this, Bool sensitive) {
	
	gtk_widget_set_sensitive(this->class->__getWidget(this), sensitive);


}

Bool __gtk_Widget_isRealized(struct gtk_Widget*  this) {
	
	return GTK_WIDGET_REALIZED(this->class->__getWidget(this));


}

/**
 * Realize this component on-screen, e.g. allocate resources, etc.
 * It's often not needed to call it directly, use show() instead.
 */
Void __gtk_Widget_realize(struct gtk_Widget*  this) {
	
	gtk_widget_realize(this->class->__getWidget(this));


}

/**
 * Force the repaint of this widget
 */
Void __gtk_Widget_forceRepaint_Bool(struct gtk_Widget*  this, Bool childrenToo) {
	
	while(__gtk_Gtk_eventsPending()) {
		__gtk_Gtk_mainIteration();
	}
	gdk_window_invalidate_rect(this->class->__getWidget(this)->window, NULL, childrenToo);
	gdk_window_process_updates(this->class->__getWidget(this)->window, childrenToo);


}

/**
 * Shows this widget on-screen.
 */
Void __gtk_Widget_show(struct gtk_Widget*  this) {
	
	gtk_widget_show(this->class->__getWidget(this));


}

/**
 * Shows this widget on-screen and all its children.
 */
Void __gtk_Widget_showAll(struct gtk_Widget*  this) {
	
	gtk_widget_show_all(this->class->__getWidget(this));


}

/**
 * Hides this widget
 */
Void __gtk_Widget_hide(struct gtk_Widget*  this) {
	
	gtk_widget_hide(this->class->__getWidget(this));


}

Void __gtk_Widget_destroy(struct gtk_Widget*  this) {
	
	gtk_widget_destroy(this->class->__getWidget(this));


}

/**
 * set the position of this wdiget
 * @param x the x coordinate of the desired position for this widget, or
 * -1 for default position
 * @param y the y coordinate of the desired position for this widget, or
 * -1 for default position
 */
Void __gtk_Widget_setPosition_gint_gint(struct gtk_Widget*  this, gint x, gint y) {
	
	gtk_widget_set_usize(this->class->__getWidget(this), x, y);


}

/**
 * set the size of this widget
 * @param width the desired width for this widget, or -1 for the default
 * @param height the desired height for this widget, or -1 for the default
 */
Void __gtk_Widget_setUSize_gint_gint(struct gtk_Widget*  this, gint width, gint height) {
	
	gtk_widget_set_usize(this->class->__getWidget(this), width, height);


}

/**
 * Adjust the event mask of this widget
 */
Void __gtk_Widget_setEvents_Int(struct gtk_Widget*  this, Int eventMask) {
	
	gtk_widget_set_events(this->class->__getWidget(this), eventMask);


}

/**
 * Return the size of the window, as a GtkAllocation (a GdkRectangle, really)
 */
GtkAllocation __gtk_Widget_getAllocation(struct gtk_Widget*  this) {
	
	return this->class->__getWidget(this)->allocation;


}

/**
 * The height of this window
 */
Int __gtk_Widget_getWidth(struct gtk_Widget*  this) {
	
	return this->class->__getWidget(this)->allocation.width;


}

/**
 * The height of this window
 */
Int __gtk_Widget_getHeight(struct gtk_Widget*  this) {
	
	return this->class->__getWidget(this)->allocation.height;


}

struct gtk_Style*  __gtk_Widget_getStyle(struct gtk_Widget*  this) {
	
	return __gtk_Style_new_GtkStyle__star(gtk_widget_get_style(this->class->__getWidget(this)));


}
