/*
 * Generated by ooc, the Object-Oriented C compiler, by Amos Wenger, 2009
 */

// OOC dependencies
#include "version.h"
 Int main() {

	GC_init();	
#ifdef __linux__
printf("Running on Linux =)\n");
#else
printf("Not running on Linux =(\n");
#endif
 
}
