/*
 * Generated by ooc, the Object-Oriented C compiler, by Amos Wenger, 2009
 */

// OOC dependencies
#include "Vector2f.h"
//  libm is actually the math library 

/*
 * Definition of class math.Vector2f
 */

Float math_Vector2f_EPSILON = 1.0E-6f;

math_Vector2f__class math_Vector2f__classInstance;


Float __math_Vector2f_squaredLength(struct math_Vector2f*  this) {
	
	return(this->x  *  this->x  +  this->y  *  this->y);


}

Float __math_Vector2f_length(struct math_Vector2f*  this) {
	
	return sqrt(this->x  *  this->x  +  this->y  *  this->y);


}

Void __math_Vector2f_reverse(struct math_Vector2f*  this) {
	
	this->x =  - this->x;
	this->y =  - this->y;


}

Void __math_Vector2f_normalize(struct math_Vector2f*  this) {
	
	Float _length = this->class->__length(this);
	if(_length < 0) {
		if(_length >  - math_Vector2f_EPSILON) {
			return;
		}
	}
	else {
		if(_length < math_Vector2f_EPSILON) {
			return;
		}
	}
	this->x /= _length;
	this->y /= _length;


}

Void __math_Vector2f_scale_Float(struct math_Vector2f*  this, Float newLength) {
	
	Float _length = this->class->__length(this);
	if(_length < 0) {
		if(_length >  - math_Vector2f_EPSILON) {
			return;
		}
	}
	else {
		if(_length < math_Vector2f_EPSILON) {
			return;
		}
	}
	this->x /= _length / newLength;
	this->y /= _length / newLength;


}

Void __math_Vector2f_set_Float_Float(struct math_Vector2f*  this, Float x, Float y) {
	
	this->x = x;
	this->y = y;


}

Void __math_Vector2f_set_math_Vector2f(struct math_Vector2f*  this, struct math_Vector2f*  t) {
	
	this->x = t->x;
	this->y = t->y;


}

Void __math_Vector2f_add_math_Vector2f(struct math_Vector2f*  this, struct math_Vector2f*  t) {
	
	this->x += t->x;
	this->y += t->y;


}

Void __math_Vector2f_sub_math_Vector2f(struct math_Vector2f*  this, struct math_Vector2f*  t) {
	
	this->x -= t->x;
	this->y -= t->y;


}

Void __math_Vector2f_mul_Float(struct math_Vector2f*  this, Float f) {
	
	this->x *= f;
	this->y *= f;


}

Void __math_Vector2f_div_Float(struct math_Vector2f*  this, Float f) {
	
	this->x /= f;
	this->y /= f;


}

Void __math_Vector2f_add_Float_Float(struct math_Vector2f*  this, Float x, Float y) {
	
	this->x += x;
	this->y += y;


}

Void __math_Vector2f_add_Int_Int(struct math_Vector2f*  this, Int x, Int y) {
	
	this->x += x;
	this->y += y;


}

Void __math_Vector2f_sub_Float_Float(struct math_Vector2f*  this, Float x, Float y) {
	
	this->x -= x;
	this->y -= y;


}

Void __math_Vector2f_sub_Int_Int(struct math_Vector2f*  this, Int x, Int y) {
	
	this->x -= x;
	this->y -= y;


}

String __math_Vector2f_repr(struct math_Vector2f*  this) {
	
	const Int BUFFER_SIZE = 50;
	String buffer = GC_malloc(BUFFER_SIZE);
	snprintf(buffer, BUFFER_SIZE, "(%.3f, %.3f)", this->x, this->y);
	return buffer;


}

struct math_Vector2f*  __math_Vector2f_new() {

	math_Vector2f this = GC_malloc(sizeof(struct math_Vector2f));

	if(math_Vector2f__classInstance == NULL) {
		math_Vector2f__classInstance = GC_malloc(sizeof(struct math_Vector2f__class));
		math_Vector2f__classInstance ->name = "math.Vector2f";
	}
	this->class = math_Vector2f__classInstance;

	this->class->__squaredLength = (Float (*)(struct math_Vector2f* )) &__math_Vector2f_squaredLength;
	this->class->__length = (Float (*)(struct math_Vector2f* )) &__math_Vector2f_length;
	this->class->__reverse = (Void (*)(struct math_Vector2f* )) &__math_Vector2f_reverse;
	this->class->__normalize = (Void (*)(struct math_Vector2f* )) &__math_Vector2f_normalize;
	this->class->__scale_Float = (Void (*)(struct math_Vector2f* , Float)) &__math_Vector2f_scale_Float;
	this->class->__set_Float_Float = (Void (*)(struct math_Vector2f* , Float, Float)) &__math_Vector2f_set_Float_Float;
	this->class->__set_math_Vector2f = (Void (*)(struct math_Vector2f* , struct math_Vector2f* )) &__math_Vector2f_set_math_Vector2f;
	this->class->__add_math_Vector2f = (Void (*)(struct math_Vector2f* , struct math_Vector2f* )) &__math_Vector2f_add_math_Vector2f;
	this->class->__sub_math_Vector2f = (Void (*)(struct math_Vector2f* , struct math_Vector2f* )) &__math_Vector2f_sub_math_Vector2f;
	this->class->__mul_Float = (Void (*)(struct math_Vector2f* , Float)) &__math_Vector2f_mul_Float;
	this->class->__div_Float = (Void (*)(struct math_Vector2f* , Float)) &__math_Vector2f_div_Float;
	this->class->__add_Float_Float = (Void (*)(struct math_Vector2f* , Float, Float)) &__math_Vector2f_add_Float_Float;
	this->class->__add_Int_Int = (Void (*)(struct math_Vector2f* , Int, Int)) &__math_Vector2f_add_Int_Int;
	this->class->__sub_Float_Float = (Void (*)(struct math_Vector2f* , Float, Float)) &__math_Vector2f_sub_Float_Float;
	this->class->__sub_Int_Int = (Void (*)(struct math_Vector2f* , Int, Int)) &__math_Vector2f_sub_Int_Int;
	this->class->__repr = (String (*)(struct math_Vector2f* )) &__math_Vector2f_repr;
	
	this->x = 0;
	this->y = 0;

	return this;


}

struct math_Vector2f*  __math_Vector2f_new_Float_Float(Float x, Float y) {

	math_Vector2f this = GC_malloc(sizeof(struct math_Vector2f));

	if(math_Vector2f__classInstance == NULL) {
		math_Vector2f__classInstance = GC_malloc(sizeof(struct math_Vector2f__class));
		math_Vector2f__classInstance ->name = "math.Vector2f";
	}
	this->class = math_Vector2f__classInstance;

	this->class->__squaredLength = (Float (*)(struct math_Vector2f* )) &__math_Vector2f_squaredLength;
	this->class->__length = (Float (*)(struct math_Vector2f* )) &__math_Vector2f_length;
	this->class->__reverse = (Void (*)(struct math_Vector2f* )) &__math_Vector2f_reverse;
	this->class->__normalize = (Void (*)(struct math_Vector2f* )) &__math_Vector2f_normalize;
	this->class->__scale_Float = (Void (*)(struct math_Vector2f* , Float)) &__math_Vector2f_scale_Float;
	this->class->__set_Float_Float = (Void (*)(struct math_Vector2f* , Float, Float)) &__math_Vector2f_set_Float_Float;
	this->class->__set_math_Vector2f = (Void (*)(struct math_Vector2f* , struct math_Vector2f* )) &__math_Vector2f_set_math_Vector2f;
	this->class->__add_math_Vector2f = (Void (*)(struct math_Vector2f* , struct math_Vector2f* )) &__math_Vector2f_add_math_Vector2f;
	this->class->__sub_math_Vector2f = (Void (*)(struct math_Vector2f* , struct math_Vector2f* )) &__math_Vector2f_sub_math_Vector2f;
	this->class->__mul_Float = (Void (*)(struct math_Vector2f* , Float)) &__math_Vector2f_mul_Float;
	this->class->__div_Float = (Void (*)(struct math_Vector2f* , Float)) &__math_Vector2f_div_Float;
	this->class->__add_Float_Float = (Void (*)(struct math_Vector2f* , Float, Float)) &__math_Vector2f_add_Float_Float;
	this->class->__add_Int_Int = (Void (*)(struct math_Vector2f* , Int, Int)) &__math_Vector2f_add_Int_Int;
	this->class->__sub_Float_Float = (Void (*)(struct math_Vector2f* , Float, Float)) &__math_Vector2f_sub_Float_Float;
	this->class->__sub_Int_Int = (Void (*)(struct math_Vector2f* , Int, Int)) &__math_Vector2f_sub_Int_Int;
	this->class->__repr = (String (*)(struct math_Vector2f* )) &__math_Vector2f_repr;
	
	this->x = x;
	this->y = y;

	return this;


}

struct math_Vector2f*  __math_Vector2f_new_math_Vector2f(struct math_Vector2f*  copy) {

	math_Vector2f this = GC_malloc(sizeof(struct math_Vector2f));

	if(math_Vector2f__classInstance == NULL) {
		math_Vector2f__classInstance = GC_malloc(sizeof(struct math_Vector2f__class));
		math_Vector2f__classInstance ->name = "math.Vector2f";
	}
	this->class = math_Vector2f__classInstance;

	this->class->__squaredLength = (Float (*)(struct math_Vector2f* )) &__math_Vector2f_squaredLength;
	this->class->__length = (Float (*)(struct math_Vector2f* )) &__math_Vector2f_length;
	this->class->__reverse = (Void (*)(struct math_Vector2f* )) &__math_Vector2f_reverse;
	this->class->__normalize = (Void (*)(struct math_Vector2f* )) &__math_Vector2f_normalize;
	this->class->__scale_Float = (Void (*)(struct math_Vector2f* , Float)) &__math_Vector2f_scale_Float;
	this->class->__set_Float_Float = (Void (*)(struct math_Vector2f* , Float, Float)) &__math_Vector2f_set_Float_Float;
	this->class->__set_math_Vector2f = (Void (*)(struct math_Vector2f* , struct math_Vector2f* )) &__math_Vector2f_set_math_Vector2f;
	this->class->__add_math_Vector2f = (Void (*)(struct math_Vector2f* , struct math_Vector2f* )) &__math_Vector2f_add_math_Vector2f;
	this->class->__sub_math_Vector2f = (Void (*)(struct math_Vector2f* , struct math_Vector2f* )) &__math_Vector2f_sub_math_Vector2f;
	this->class->__mul_Float = (Void (*)(struct math_Vector2f* , Float)) &__math_Vector2f_mul_Float;
	this->class->__div_Float = (Void (*)(struct math_Vector2f* , Float)) &__math_Vector2f_div_Float;
	this->class->__add_Float_Float = (Void (*)(struct math_Vector2f* , Float, Float)) &__math_Vector2f_add_Float_Float;
	this->class->__add_Int_Int = (Void (*)(struct math_Vector2f* , Int, Int)) &__math_Vector2f_add_Int_Int;
	this->class->__sub_Float_Float = (Void (*)(struct math_Vector2f* , Float, Float)) &__math_Vector2f_sub_Float_Float;
	this->class->__sub_Int_Int = (Void (*)(struct math_Vector2f* , Int, Int)) &__math_Vector2f_sub_Int_Int;
	this->class->__repr = (String (*)(struct math_Vector2f* )) &__math_Vector2f_repr;
	
	this->x = copy->x;
	this->y = copy->y;

	return this;


}
