/*
 * Generated by ooc, the Object-Oriented C compiler, by Amos Wenger, 2009
 */

// OOC dependencies
#include "Anagrams.h"
  with  io.stdout.(print,  println);
Int size;
String string;

Int main() {

	GC_init();	


}

with string {
	
	that = "Java Source and Support";
	__doAnagram_Int(that.length);
}

Void __doAnagram_Int(Int newSize) {
	
	if(newSize == 1) return;
	//  if too small, return 

	//  for each position, 

	for(int i = 0; i < newSize; i += 1)  {
		__doAnagram_Int(newSize -1);
		//  anagram remaining 

		if(newSize == 2) __display();
		__rotate_Int(newSize);
		//  rotate word 

	}


}
//  rotate left all chars from position to end 


Void __rotate_Int(Int newSize) {
	


}

with string {
	//  save first letter 

	Char temp =[size  -  newSize];
	// shift others left 

	for(int i = (position + 1); i < size; i += 1)  {[i -1] =[i];
	}
	// put first on right 
[i -1] = temp;
}

Void __display() {
	
	static Int count = 0;
	printf(% "${++count} $string\n");


}
