/*
 * Generated by ooc, the Object-Oriented C compiler, by Amos Wenger, 2009
 */

// OOC dependencies
#include "OocLib.h"
 Object GC_calloc(Int nmemb, SizeT size) {
	
	SizeT memsize = nmemb  *  size;
	Object tmp = GC_malloc(memsize);
	memset(tmp, 0, memsize);
	return tmp; 
}
