/*
 * Generated by ooc, the Object-Oriented C compiler, by Amos Wenger, 2009
 */

// OOC dependencies
#include "Iterator.h"

/*
 * Definition of class structs.Iterator
 */

structs_Iterator__class structs_Iterator__classInstance;

