/*
 * Generated by ooc, the Object-Oriented C compiler, by Amos Wenger, 2009
 */

// OOC dependencies
#include "Iterable.h"

/*
 * Definition of class structs.Iterable
 */

structs_Iterable__class structs_Iterable__classInstance;

