/*
 * Generated by ooc, the Object-Oriented C compiler, by Amos Wenger, 2009
 */

// OOC dependencies
#include "List.h"


/**
 * List interface for a data container
 */

/*
 * Definition of class structs.List
 */

structs_List__class structs_List__classInstance;


/**
 * Appends the specified element to the end of this list.
 */


/**
 * Inserts the specified element at the specified position in
 * this list.
 */


/**
 * Appends all of the elements in the specified Collection to the
 * end of this list, in the order that they are returned by the
 * specified Collection's Iterator.
 */
Void __structs_List_addAll_List(struct structs_List*  this, struct structs_List*  list) {
	
	this->class->__addAll_Int_List(this, 0, list);


}

/**
 * Inserts all of the elements in the specified Collection into
 * this list, starting at the specified position.
 */
Void __structs_List_addAll_Int_List(struct structs_List*  this, Int index, struct structs_List*  list) {
	
	for(int i = 
		0; i <  list->class->__size(list); i += 1)  {
		this->class->__add_Object(this, list->class->__get_Int(list, i));
	}


}

/**
 * Removes all of the elements from this list.
 */


/**
 * Removes the last element of the list, if any (=non-empty list).
 * @return true if it has removed an element, false if the list
 * was empty.
 */
Bool __structs_List_removeLast(struct structs_List*  this) {
	
	Int size = this->class->__size(this);
	if(size > 0) {
		this->class->__remove_Int(this, size -1);
		return true;
	}
	else {
		return false;
	}


}

/**
 * @return true if this list contains the specified element.
 */
Bool __structs_List_contains_Object(struct structs_List*  this, Object element) {
	
	return(this->class->__indexOf_Object(this, element) != -1);


}

/**
 * @return the element at the specified position in this list.
 */


/**
 * @return the index of the first occurence of the given argument,
 * (testing for equality using the equals method), or -1 if not found
 */


/**
 * @return true if this list has no elements.
 */
Bool __structs_List_isEmpty(struct structs_List*  this) {
	
	return(this->class->__size(this) == 0);


}

/**
 * @return the index of the last occurrence of the specified object
 * in this list.
 */


/**
 * Removes the element at the specified position in this list.
 * @return the element just removed
 */


/**
 * Removes a single instance of the specified element from this list,
 * if it is present (optional operation).
 * @return true if at least one occurence of the element has been
 * removed
 */


/**
 * Replaces the element at the specified position in this list with
 * the specified element.
 */


/**
 * @return the number of elements in this list.
 */


/**
 * @return the number of elements this list can hold without needing
 * to grow.
 */

