/*
 * Generated by ooc, the Object-Oriented C compiler, by Amos Wenger, 2009
 */

// OOC dependencies
#include "EventDispatcher.h"


/**
 */

/*
 * Definition of class event.EventDispatcher
 */

event_EventDispatcher__class event_EventDispatcher__classInstance;


Void __event_EventDispatcher_addEventListener_Func_Int(struct event_EventDispatcher*  this, Func listener, Int eventType) {
	
	
	struct structs_Iterator*  Iterator_iter =  this->listeners->class->__iterator( this->listeners);
	while(Iterator_iter->class->__hasNext(Iterator_iter)) {
		struct event_EventListener*  eventListener = Iterator_iter->class->__next(Iterator_iter);
		// WTF ? 

		// if(eventListener.@listener == listener && eventListener.eventType == eventType) { 

		if(eventListener->listener == listener && eventListener->eventType == eventType) {
			return;
		}
	}
	this->listeners->class->__add_Object(this->listeners, __event_EventListener_new_Func_Int(listener, eventType));


}

Bool __event_EventDispatcher_removeEventListener_Func_Int(struct event_EventDispatcher*  this, Func listener, Int eventType) {
	
	
	struct structs_Iterator*  Iterator_iter =  this->listeners->class->__iterator( this->listeners);
	while(Iterator_iter->class->__hasNext(Iterator_iter)) {
		struct event_EventListener*  eventListener = Iterator_iter->class->__next(Iterator_iter);
		// WTF ? 

		// if(eventListener.@listener == listener && eventListener.eventType == eventType) { 

		if(eventListener->listener == listener && eventListener->eventType == eventType) {
			this->listeners->class->__removeElement_Object(this->listeners, eventListener);
			return true;
		}
	}
	return false;


}

Void __event_EventDispatcher_dispatchEvent_Event(struct event_EventDispatcher*  this, struct event_Event*  event) {
	
	event->target = this;
	
	struct structs_Iterator*  Iterator_iter =  this->listeners->class->__iterator( this->listeners);
	while(Iterator_iter->class->__hasNext(Iterator_iter)) {
		struct event_EventListener*  listener = Iterator_iter->class->__next(Iterator_iter);
		if(listener->eventType == event->type) listener->listener(event);
	}


}
/*
 * Definition of class event.EventListener
 */

event_EventListener__class event_EventListener__classInstance;


struct event_EventListener*  __event_EventListener_new_Func_Int(Func listener, Int eventType) {

	event_EventListener this = GC_malloc(sizeof(struct event_EventListener));

	if(event_EventListener__classInstance == NULL) {
		event_EventListener__classInstance = GC_malloc(sizeof(struct event_EventListener__class));
		event_EventListener__classInstance->name = "event.EventListener";
		event_EventListener__classInstance->simpleName = "EventListener";
	}
	this->class = event_EventListener__classInstance;

	
	this->listener = listener;
	this->eventType = eventType;

	return this;


}
