/*
 * Generated by ooc, the Object-Oriented C compiler, by Amos Wenger, 2009
 */

// OOC dependencies
#include "Event.h"

/*
 * Definition of class event.Event
 */

event_Event__class event_Event__classInstance;


struct event_Event*  __event_Event_new_Int(Int type) {

	event_Event this = GC_malloc(sizeof(struct event_Event));

	if(event_Event__classInstance == NULL) {
		event_Event__classInstance = GC_malloc(sizeof(struct event_Event__class));
		event_Event__classInstance->name = "event.Event";
		event_Event__classInstance->simpleName = "Event";
	}
	this->class = event_Event__classInstance;

	
	this->type = type;

	return this;


}
