/*
 * Generated by ooc, the Object-Oriented C compiler, by Amos Wenger, 2009
 */

// OOC dependencies
#include "glut.h"
 static Bool test;
/*
 * Definition of class Color
 */

Color__class Color__classInstance;


struct Color*  __Color_new_Double_Double_Double_Double(Double r, Double g, Double b, Double a) {

	Color this = GC_malloc(sizeof(struct Color));

	if(Color__classInstance == NULL) {
		Color__classInstance = GC_malloc(sizeof(struct Color__class));
		Color__classInstance ->name = "Color";
	}
	this->class = Color__classInstance;

	
	this->r = r;
	this->g = g;
	this->b = b;
	this->a = a;

	return this;


}
/*
 * Definition of class Window
 */

Window__class Window__classInstance;


Void __Window_show(struct Window*  this) {
	
	glutInitDisplayMode(GLUT_DEPTH | GLUT_RGBA);
	glutInitWindowPosition(0, 0);
	glutInitWindowSize(this->width, this->height);
	glutCreateWindow(this->name);
	glutDisplayFunc(this->class->__displayWrapper);
	this->clearColor = __Color_new_Double_Double_Double_Double(1.0, 0.5, 0.2, 0.0);


}

Void __Window_updateClearColor(struct Window*  this) {
	
	this->clearColor->r = this->clearColor->r  +  0.05;
	if(this->clearColor->r > 1.0) {
		this->clearColor->r = 0.0;
	}
	glClearColor(this->clearColor->r, this->clearColor->g, this->clearColor->b, this->clearColor->a);


}

Void __Window_displayWrapper() {
	
	instance->class->__display(instance);


}

Void __Window_display(struct Window*  this) {
	
	this->class->__updateClearColor;
	glClear(GL_COLOR_BUFFER_BIT);
	glutSwapBuffers();
	if(test) {
		printf("In test mode, exiting gracefully =)\n");
		exit(0);
	}


}

struct Window*  __Window_new_String_Int_Int(String name, Int width, Int height) {

	Window this = GC_malloc(sizeof(struct Window));

	if(Window__classInstance == NULL) {
		Window__classInstance = GC_malloc(sizeof(struct Window__class));
		Window__classInstance ->name = "Window";
	}
	this->class = Window__classInstance;

	this->class->__show = (Void (*)(struct Window* )) &__Window_show;
	this->class->__updateClearColor = (Void (*)(struct Window* )) &__Window_updateClearColor;
	
	this->class->__display = (Void (*)(struct Window* )) &__Window_display;
	
	this->name = name;
	this->width = width;
	this->height = height;
	this->instance = this;

	return this;


}
/*
 * Definition of class Application
 */

Application__class Application__classInstance;


Void __Application_run(struct Application*  this) {
	
	this->window->class->__show(this->window);
	glutMainLoop();


}

struct Application*  __Application_new_Int_String__array(Int argc, String argv[]) {

	Application this = GC_malloc(sizeof(struct Application));

	if(Application__classInstance == NULL) {
		Application__classInstance = GC_malloc(sizeof(struct Application__class));
		Application__classInstance ->name = "Application";
	}
	this->class = Application__classInstance;

	this->class->__run = (Void (*)(struct Application* )) &__Application_run;
	
	glutInit(& argc, argv);
	this->window = __Window_new_String_Int_Int("My super window", 1024, 768);

	return this;


}

Int main(Int argc, String argv[]) {

	GC_init();	
	if(argc >= 2 && strcmp(argv[1], "--test") == 0) {
		test = true;
	}
	struct Application*  Application_Application_new = __Application_new_Int_String__array(argc, argv);
	Application_Application_new->class->__run(Application_Application_new);


}
