// Generated by ooc, the Object-Oriented C compiler, by Amos Wenger, 2009

// Boehm's GC (Garbage Collector)
#include <gc.h>
#define malloc GC_MALLOC
// OOC dependencies
#include "glut-workaround.h"
#include <lightning.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <GL/gl.h>
#include <GL/glut.h>
#define null 0
Color Color_new_double_double_double_double(double r, double g, double b, double a) {
	Color this = malloc(sizeof(struct Color));
	this->r = r;
	this->g = g;
	this->b = b;
	this->a = a;
	return this;
}

void Window_show(Window this) {
	glutInitDisplayMode(GLUT_DEPTH | GLUT_RGBA);
	glutInitWindowPosition(0, 0);
	glutInitWindowSize(this->width,this->height);
	glutCreateWindow(this->name);
	glutDisplayFunc((void(*)(void)) this->display);
	this->clearColor = Color_new_double_double_double_double(1.0, 0.5, 0.2, 0.0);
}

void Window_updateClearColor(Window this) {
	this->clearColor->r = this->clearColor->r + 0.05;
	if(this->clearColor->r > 1.0){
		this->clearColor->r = 0.0;
	}
	 glClearColor(this->clearColor->r,this->clearColor->g,this->clearColor->b,this->clearColor->a);
}

void Window_display(Window this) {
	this->updateClearColor(this);
	glClear(GL_COLOR_BUFFER_BIT);
	glutSwapBuffers();
}

typedef void(*typeof_Window_display)(void);

typeof_Window_display assemble_Window_display(Window this) {

	jit_insn *codeBuffer = malloc(1024 * sizeof(jit_insn));
	typeof_Window_display generatedFunction;
	char *start, *end;

	generatedFunction = (typeof_Window_display) (jit_set_ip(codeBuffer).vptr);
	start = jit_get_ip().ptr;
	jit_prolog(1); // it's always 1
	jit_prepare(1); // number of arguments
	jit_movi_p(JIT_R0, this);
	jit_pusharg_p(JIT_R0);
	jit_finish(Window_display);
	jit_ret(); // return
	end = jit_get_ip().ptr;

	jit_flush_code(start, end);

	return generatedFunction;

}

Window Window_new_String_int_int(String name, int width, int height) {
	Window this = malloc(sizeof(struct Window));
	this->show = &Window_show;
	this->updateClearColor = &Window_updateClearColor;
	this->display = assemble_Window_display(this);
	this->name = name;
	this->width = width;
	this->height = height;
	return this;
}

void Application_run(Application this) {
	printf("Running application !\n");
	this->window->show(this->window);
	glutMainLoop();
}

Application Application_new_int__star_char__star__star(int * argc, char ** argv) {
	Application this = malloc(sizeof(struct Application));
	this->run = &Application_run;
	glutInit(argc,argv);
	this->window = Window_new_String_int_int("My super window", 1024, 768);
	return this;
}

int main(int argc, char ** argv) {
	GC_INIT();
	Application app = Application_new_int__star_char__star__star( &argc,argv);
	app->run(app);
}

